name: "Terraform 3 tier infra"

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true # Silences Node 20 runtime alerts globally

on:
  push:
    branches:
      - /*
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy"
        required: true
        default: "Development"
        type: choice
        options:
          - Development
          - stage
          - master
          - destroy
      operation:
        description: "Select the operation to run"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform_pipeline:
    name: "Execute Terraform Build"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'apply')
    # environment: ${{ github.event.inputs.deploy_env }}
    # if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'apply')

    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref_name == 'Development' && 'Development' || github.ref_name == 'stage' && 'stage' || github.ref_name == 'destroy' && 'destroy' || 'master') }}

    # Declaring credentials here makes them available to ALL steps automatically
    env:
      GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform Initialize
        run: terraform init -input=false -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate" -reconfigure -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  terraform_pipeline_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/destroy' || (github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'destroy')
    environment: ${{ github.event.inputs.environment }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform Initialize for Destroy
        run: |
          terraform init -input=false -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate" -reconfigure -upgrade

      # - name: Wait before destroy
      #   run: |
      #     echo "Waiting 2 minutes before running destroy..."
      #     sleep 120

      - name: Terraform Destroy
        run: terraform destroy --auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
