name: "Terraform 3 tier infra"

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true # Silences Node 20 runtime alerts globally

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      operation:
        description: "Operation to run: apply or destroy"
        required: true
        default: "apply"
      deploy_env:
        description: "Deployment environment to target (Production, UAT, Development)"
        required: true
        default: "Development"

jobs:
  terraform_pipeline:
    name: "Execute Terraform Build"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.deploy_env }}
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'apply')

    # Declaring credentials here makes them available to ALL steps automatically
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform Initialize
        run: |
          terraform init -input=false -backend-config="key=${{ toLower(github.event.inputs.deploy_env) }}/terraform.tfstate" -reconfigure -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ toLower(github.event.inputs.deploy_env) }}"

      - name: Terraform Apply
        run: terraform apply --auto-approve -var="environment=${{ toLower(github.event.inputs.deploy_env) }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }} # Kept here as it's only needed for git pulls

  terraform_pipeline_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/destroy' || (github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'destroy')
    environment: ${{ github.event.inputs.deploy_env }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform Initialize for Destroy
        run: |
          terraform init -input=false -backend-config="key=${{ toLower(github.event.inputs.deploy_env) }}/terraform.tfstate" -reconfigure -upgrade

      - name: Terraform Destroy
        run: terraform destroy --auto-approve -var="environment=${{ toLower(github.event.inputs.deploy_env) }}"
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
